package za.co.entelect.challenge.ai.opta;
    dialect "java"

import org.optaplanner.core.api.score.buildin.simple.SimpleScoreHolder;

import za.co.entelect.challenge.ai.opta.*;

global SimpleScoreHolder scoreHolder;

rule "distanceToPreviousStandstill"
    when
        $visit : Visit(previousStandstill != null, $distanceToPreviousStandstill : distanceToPreviousStandstill)
    then
        scoreHolder.addConstraintMatch(kcontext, - $distanceToPreviousStandstill);
end

rule "distanceFromLastVisitToDomicile"
    when
        $visit : Visit(previousStandstill != null)
        not Visit(previousStandstill == $visit)
        $domicile : Domicile()
    then
        scoreHolder.addConstraintMatch(kcontext, - $visit.getDistanceTo($domicile));
end
