package za.co.entelect.challenge.ai.opta;
    dialect "java"

import org.optaplanner.core.api.score.buildin.simple.SimpleScoreHolder;

import za.co.entelect.challenge.ai.opta.*;

global SimpleScoreHolder scoreHolder;

rule "distanceToPreviousStandstill"
    when
        $visit : Visit(previousCell != null, $distanceToPreviousCell : distanceToPreviousCell)
    then
        scoreHolder.addConstraintMatch(kcontext, - $distanceToPreviousCell);
end